<?php

namespace front4wp\baseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentmetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentmetaRepository extends EntityRepository
{
}
