<?php

namespace front4wp\baseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermTaxonomyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermTaxonomyRepository extends EntityRepository
{
}
